version: "2.3"

services:
  db:
    image: mongo:4.2.5-bionic
    volumes:
      - mongodb:/data/db
      - mongoconfig:/data/configdb
  server:
    build: ./server
    volumes:
      - vod_server:/app
    ports:
      - 4880:5000
    environment:
      - FFMPEG_PATH=ffmpeg
      - FFPROBE_PATH=ffprobe
      - VOD_FOLDER_PATH=/app/vod
      - PREVOD_FOLDER_PATH=/app/prevod
      - MONGO_PATH=mongodb://db:27017
      - MONGO_DB_NAME=sim
    depends_on:
      - db
    cpu_percent: 100
  web:
    build: ./client
    ports:
      - 4881:3000
    depends_on:
      - server

volumes:
  vod_server:
    driver: local
  mongodb:
    driver: local
  mongoconfig:
    driver: local
